### ISSUE TITLE
Add menu dynamically issue

### ISSUE THREAD

**Issue by turtlebe** [otifsolutions/aclmenu#1]
Hi, thank you for your package.
I love this package and really thank you.
But I have trouble with adding additional menu items.
After seeded default menu items, I needed to add some additional items with permissions with something like a migration file or seed file.
But I don't know how to do it.
Any can help me?
Thanks.

**Comment by junaidmaqbutt** [comment]
@jinguohao1991 , You can create seeds for managing permissions and adding more to the menu here is the process. 


Step 1 -Create User Role(s)

`\OTIFSolutions\ACLMenu\Models\UserRole::create(['name' => 'NAME_GOES_HERE']);  `

Step 2 - Create Menu Item(s)

```
\OTIFSolutions\ACLMenu\Models\MenuItem::create(['parent_id' => 0,'icon' => 'fa-icon','name' => 'Dashboard','route' => '/dashboard', 'generate_permission' => 'MANAGE_ONLY', 'icon_svg' => 'dashboard.svg'])->user_roles()->sync([1]);
```

The above command will add this menu item to user roles with id 1 can be done by name and so on as per requirement.

Step 3 execute available command to generate permissions for the made menu items
`php artisan aclmenu:refresh`


Step 4 add permissions to user role as per requirement

```
$userRole = \OTIFSolutions\ACLMenu\Models\UserRole::where(['name' => 'NAME_GOES_HERE'])->first();
$permissions = \OTIFSolutions\ACLMenu\Models\Permission::whereIn('menu_item_id',$userRole->menu_items()->pluck('id'))->pluck('id');
$userRole->permissions()->sync($permissions);
```

In step 4 you can do customizations. Like instead of getting all permissions from the table by id. you can do something like this 

`$permissions = Permission::where('name','like','%_dashboard')`

That's it a basic menu with rights/permissions is done.


PS: You should do all this in different seeds files to have a smooth ride. Call the command `Artisan::call('aclmenu:refresh');` after user role and menu item seeders so that it can generate permissions
